# Generated by Django 5.2.7 on 2025-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(),
        ),
    ]
